### ISSUE TITLE
Add repository Topics to enable discovery by topic search, e.g. "topic:template topic:vapor topic:vapor4"

### ISSUE THREAD

**Issue by marc-medley** [vapor/template#115]
**Is your feature request related to a problem?**

It would be helpful to have a way to search for Vapor Templates.

For example: [search "topic:template topic:vapor"](https://github.com/search?q=topic%3Atemplate+topic%3Avapor&type=repositories&s=updated&o=desc)

It would also be helpful if `topic:vapor4` were also added to differentiate current from legacy template.

**Describe the solution you'd like**

I would like to see topics `vapor`, `vapor4`, and `template` added to the following repositories:

- https://github.com/vapor/template
- https://github.com/vapor/template-bare
- https://github.com/vapor/template-fluent-mysql
- https://github.com/vapor/template-fluent-postgres
- https://github.com/vapor/template-fluent-postgres-leaf
- https://github.com/vapor/template-fluent-sqlite

Thank you.

**Comment by 0xTim** [comment]
I've updated the topics to add `vapor` `server-side-swift` and `template`

I left off `vapor-4` because the legacy templates should all be archived by now and any new versions will break this
