### ISSUE TITLE
Support setting `MTELG.singleton` as Swift Concurrency executor

### ISSUE THREAD

**Issue by MahdiBM** [vapor/template#122]
See https://github.com/apple/swift-nio/pull/2564.
This is not tagged as of creating this issue.

**Comment by 0xTim** [comment]
We don't need this due to https://github.com/vapor/vapor/releases/tag/4.91.0 right?

**Comment by 0xTim** [comment]
Ohhh I misread this - carry on nothing to see here 😅

**Comment by 0xTim** [comment]
Done in #131
