### ISSUE TITLE
Blank new project can't parse Package.swift file

### ISSUE THREAD

**Issue by maxbritto** [vapor/template#16]
Hello,
after creating a new project with :
```
vapor-beta new todos
```
Wether or not we activate `fluent` we cannot build using the command line nor Xcode.
The same error alway shows before starting any build :
*manifest parse error: target 'App' depends on an unknown package 'Vapor'*

I've been creating many project for the last weeks (recording a video course) and this seems to happen since commit https://github.com/vapor/template/commit/9ab71c0524e9e2da70af991501f6f46c21912573

I'm available if you need more testing.
I'm on Catalina with the Xcode 11.4 beta and Swift 5.2
Thanks

**Comment by 0xTim** [comment]
This should be fixed in the last couple of commits, let me know if you have any more issues!

**Comment by maxbritto** [comment]
It is now fixed indeed. Thanks 👍
