### ISSUE TITLE
Docker repository name case error

### ISSUE THREAD

**Issue by jasongwartz** [vapor/template#29]
When following the [hello world docs](https://docs.vapor.codes/3.0/getting-started/hello-world/), you're prompted to use the name `Hello` (note the uppercase "H") as the project title. However, the name is interpolated into the docker-compose file under the `image: ` key, and Docker image names can not include uppercase characters.

Steps to reproduce (using the latest version of Vapor):

```
$ vapor new Hello
$ cd Hello
$ docker-compose build
# ERROR: invalid reference format: repository name must be lowercase
```

A possible resolution would be to simply lowercase the [name in the docker-compose file](https://github.com/vapor/template/blob/master/docker-compose.yml#L31). I've done this manually and it seems to work - but I'm new to Vapor so I'm not sure if there are other implications. If this would work as a resolution, I'm happy to try and submit a PR.

**Comment by 0xTim** [comment]
I think lowercasing the name in the docker compose file is sensible, happy to accept a PR!
