### ISSUE TITLE
docker-compose doesn't have a db service set when sqlite was selected during the template creation

### ISSUE THREAD

**Issue by jcbriones** [vapor/template#31]
I notice that when I create a fresh project while selecting sqlite as an option for db and run docker. The docker-compose won't build because db is not declared. Was something missing or need to be updated? Thanks

**Comment by 0xTim** [comment]
I guess it's probably never been tested since there's no point using Compose if just running with SQLite since you only need the Dockerfile. But if should probably check and not produce an invalid compose file

**Comment by jcbriones** [comment]
Yes I agree. Just reported this one just in case someone might have similar issue. But for those who doesn't know docker very well. This could cause them a headache lol.

**Comment by tanner0101** [comment]
Yup looks like we're creating an invalid docker-compose file in that case:
```sh
$ docker-compose up app
ERROR: Service 'app' depends on service 'db' which is undefined.
```
Looking into this.
