### ISSUE TITLE
Fluent drivers do not populate creating an invalid Package.swift

### ISSUE THREAD

**Issue by rpstro02** [vapor/template#5]
Creating a new project from the template does not populate the Fluent Driver correctly.

Choosing Postgres when running `new` vapor/toolbox, I expect:

`.package(url: "https://github.com/vapor/fluent-postgres-driver.git", from: "2.0.0-beta")`

but instead we get"

`.package(url: "https://github.com/vapor/fluent--driver.git", from: "-beta")`

  Also reported in vapor/toolbox#279

**Comment by tanner0101** [comment]
@rpstro02 can you try `brew upgrade vapor-beta`, that should bug have been fixed a couple versions ago. I just tested on `18.0.0-beta.25` and it seems to be working.

**Comment by rpstro02** [comment]
It’s working now with the new version
