### ISSUE TITLE
Add CI to test the template

### ISSUE THREAD

**Issue by 0xTim** [vapor/template#67]
~~Currently any PRs don't have CI, we should fix this~~

We should add some CI to test PRs that does the following:

* Build the toolbox
* Run `vapor new` for the various permutations
* Build the Docker container

We can base some of it on https://github.com/vapor/toolbox/blob/main/.github/workflows/test.yml#L8-L31

**Comment by RishiKumarRay** [comment]
@0xTim @BennyDeBock i think ci should be configured to run both on pull as well as push , i have raised a pr doing on both let me know if you want any further changes
