### ISSUE TITLE
Add a trivial `async` example route to "bare" template

### ISSUE THREAD

**Issue by gohanlon** [vapor/template#89]
In considering vapor/vapor#2858, I wonder if a trivial `async` example route should be added to the "bare" template?

Having both a non-`async` and `async` example would illustrate a fundamental concept of Vapor, and provide an easy reference when the usage intent is to spin up a new app with a single endpoint that needs to call an `async` function. Vapor newcomers may also tend to generate using a "bare" template at the start of their learning (I know I did).

Or, the existing "It works!" and "Hello, world!" examples could be changed to use the `async` form if that form is generally encouraged for new apps?

I put some thought into what a trivial additional `async` example could be:

## `Task.sleep` for a couple seconds

I like this option the most, followed by not doing any actual `async` work (the first alternative below). Having an `await` statement in the body of the function helps communicate the purpose of the example.

One drawback: a real app should never call `Task.sleep`, so this could inadvertently suggest a bad practice.

``` swift
// Sources/App/routes.swift
import Vapor

func routes(_ app: Application) throws {
    app.get { req in
        return "It works!"
    }

    app.get("hello") { req -> String in
        return "Hello, world!"
    }

    app.get("async") { req async throws -> String in
        let nanosecondsPerSec: UInt64 = 1_000_000_000
        try await Task.sleep(nanoseconds: 2 * nanosecondsPerSec)
        return "Hello, async style!"
    }
}
```

> Note: The global constant `NSEC_PER_SEC` is generally used to calculate a quantity of nanoseconds, but that's defined in `libdispatch`, which isn't really usable yet on non-Apple platforms (not that easily, at least). The nice time and duration APIs in Swift 5.7 will remove the need to calculate nanoseconds at all.

## Alternative: Don't include any actual async work

``` swift
// Sources/App/routes.swift
import Vapor

func routes(_ app: Application) throws {
    app.get { req in
        return "It works!"
    }

    app.get("hello") { req -> String in
        return "Hello, world!"
    }

    app.get("async") { req async throws -> String in
        return "Hello, async style!"
    }
}
```

This is still significantly differentiated from the non-async style "hello" function: it differs by the path segment, `async throws` in the signature, and the return value. That differentiation doesn't illustrate purpose, tho.

## Alternative: Make a URL request (bad idea)

``` swift
// Sources/App/routes.swift
import Vapor

func routes(_ app: Application) throws {
    app.get { req in
        return "It works!"
    }

    app.get("hello") { req -> String in
        return "Hello, world!"
    }

    app.get("async") { req async throws -> String in
        let urlRequest = URLRequest(url: URL(string: "http://example.com")!)
        let (data, response) = try await URLSession.shared.data(for: urlRequest)
        if let httpResponse = response as? HTTPURLResponse,
           httpResponse.statusCode != 200 {
            return "Error while fetching data"
        }
        return String(decoding: data, as: UTF8.self)
    }
}
```

A URL request is a familiar illustration, but this would depend on `FoundationNetworking` on non-Apple platforms, additionally needing:

``` swift
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
```

And, the default Dockerfile omits `FoundationNetworking`'s `libcurl4 ` dependency to produce a smaller binary by default. The default Dockerfile should definitely successfully build the freshly generated app, and adding a heavy dependency to merely gain a usage example is a non-starter.

Making a real request to a hosted service in an app template can be inconsiderate to the host unless it's specifically meant for that kind of use. (I know example.com is meant for use in sample code, but I don't know whether it's meant for code that will actually be run.)

In some scenarios, good security policy may also block outgoing network traffic by default.

Lastly, the above URL request code doesn't compile on Swift 5.6 (I only tested linux). I didn't bother investigating why, but it seems the `async` variation of `URLSession.shared.data(for:)` was introduced in Swift 5.7, or perhaps the compiler's type inference just needs some helpful annotations. The example already isn't promising and isn't that trivial, and may be even more noisy once made to work on Swift 5.6.

**Comment by 0xTim** [comment]
I'd disagree with this for the most part. The bare template is supposed to be that - essentially empty to allow people to start building without any cruft. The most I'd spring for tbh is just marking the current routes as `req async throws -> String in`. In terms of usage that's what the docs should be for

(As an aside, in almost all instances you never want to use URLSession on the server, it's not designed for that. You should use AsyncHTTPClient and Vapor's wrapper with `req.client` instead)

**Comment by gohanlon** [comment]
> The bare template is supposed to be that - essentially empty to allow people to start building without any cruft.

Is there another purpose of including the "hello" route, other than to save folks a trip to the docs for syntax? If not, maybe the "hello" route could be removed?

> The most I'd spring for tbh is just marking the current routes as `req async throws -> String in`.

That could work. I definitely don't think adding the usage example is essential, either way. Without it, a quick trip to trip to the docs for some, and some others may get the initial impression that `async`/`await` isn't well supported by Vapor.

I think it depends on whether the async syntax is preferred now or not.

But especially: If using `async`/`await` brings along any nuanced requirements or sharp edges (see below, for example), it's probably best to stick with non-`async` in the bare template to ensure users at least go to the docs before they start using `async` functions.

> ...in almost all instances you never want to use URLSession on the server...

Even in `async` contexts, I gather. Then, is it correct to say that any `async` function that performs IO should still use NIO, and that Swift Concurrency enables an alternate syntax for using NIO?

**Comment by 0xTim** [comment]
> Is there another purpose of including the "hello" route, other than to save folks a trip to the docs for syntax? If not, maybe the "hello" route could be removed?
Yeah it's just a very basic 'here's a route' you'll probably delete with the basic syntax.

`async`/`await` is definitely preferred these days. It's a shame closures can't infer whether they're async or not like they can with `throws`.

NIO for the most point (and certainly in the future) is just an implementation detail for Vapor. EventLoopFutures were an unfortunate bleed of the public API that was necessitated by having no language concurrency. In the next version of Vapor ELFs will be a thing of the past, at least from anyone using Vapor's point of view
