### ISSUE TITLE
Template app does not run

### ISSUE THREAD

**Issue by MattSanford** [vapor/template#92]
### Describe the bug

Trying to run the docker container results in an error where the app container doesn't actually start. 

### To Reproduce

1. `$ vapor new my-dockerized-app`
2. `$ cd my-dockerized-app`
3. `$ docker compose build`
4. `$ docker compose up app`

Error: 
> Error response from daemon: unable to find user vapor: no matching entries in passwd file
### Expected behavior

Both the app and the database begin running. Currently only the database begins running. 
### Environment

* Docker version: 20.10.17, build 100c701
* Vapor Framework version: 4.0.0
* Vapor Toolbox version:  18.5.1
* OS version: macOS 13.0

**Comment by 0xTim** [comment]
@MattSanford Are you trying to clone this repo? Because that won't work, you'll need to use the toolbox to generate something from this template or use one of the pre-generated templates https://blog.vapor.codes/posts/common-templates-available/

**Comment by MattSanford** [comment]
@0xTim, I don't know why I said clone. I ran the setup with 

`$ vapor new my-dockerized-app`. I'll update the original post

**Comment by 0xTim** [comment]
@MattSanford Great thanks. What options did you choose with the template?

**Comment by MattSanford** [comment]
@0xTim Fluent, Postgres, and Leaf

**Comment by 0xTim** [comment]
@MattSanford ok I can't reproduce this. What version of the toolbox, Docker and Compose are you using? Is it consistent? I've tried a couple of times, once with a dummy project name and once with the exact steps above and both worked fine

**Comment by MattSanford** [comment]
@0xTim hmm..

toolbox: 18.5.1
Docker: version 20.10.17, build 100c701
Docker compose: 3.7

**Comment by MattSanford** [comment]
@0xTim I nuked my docker install and reinstalled and now everything works? I don't know what on earth happened. Sorry for the noise!
