### ISSUE TITLE
DockerFile using swift:5.7-jammy does not work

### ISSUE THREAD

**Issue by cristiancardosodexcom** [vapor/template#95]
With DockerFile I'm unable to build with `swift:5.7-jammy` and `ubuntu:jammy`

Output error:
```
clang-13: error: unable to execute command: Killed
clang-13: error: linker command failed due to signal (use -v to see invocation)
[975/976] Linking Run
The command '/bin/sh -c swift build -c release --static-swift-stdlib' returned a non-zero code: 1
```

### Environment

Docker

* Vapor Framework version: 4.0.0
* OS version: DockerFile

### Additional context
I'm deploying to Google Cloud Build

**Comment by 0xTim** [comment]
That looks like an out of memory issue - what are the specs for the build machine?

**Comment by cristiancardosodexcom** [comment]
It's google build so default one is: 

e2-medium | 1 cpu | 4GB |

**Comment by cristiancardosodexcom** [comment]
Yeap you were right ...   machineType: 'E2_HIGHCPU_8' solved the problem.
