### ISSUE TITLE
Docker buildx crashes when cross-compiling amd64 image on Apple Silicon Mac

### ISSUE THREAD

**Issue by samalone** [vapor/template#96]
### Describe the bug

Using `docker buildx build` to cross-compile an amd64 image on an Apple Silicon Mac triggers a QEMU illegal instruction error during the `swift package resolve` step in the Dockerfile.

This seems to be related to [this issue](https://github.com/apple/swift/issues/56564) in Swift and [this issue](https://github.com/docker/for-mac/issues/5561) in Docker Desktop for Mac. Those issues are both closed, and yet the illegal instruction still occurs when building a Vapor project under Docker Desktop 4.16.2 for Mac.

### To Reproduce

On an Apple Silicon Mac running Docker Desktop 4.16.2:

1. Create a new vapor project with `vapor new buildx-test`. You do not need fluent or leaf.
2. In the project folder, run `docker buildx build --no-cache --platform linux/amd64 .`

The build fails with this output:

```
docker buildx build --no-cache --platform linux/amd64 .

[+] Building 269.9s (15/24)
 => [internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 58B                                                                                                  0.0s
 => [internal] load build definition from Dockerfile                                                                              0.0s
 => => transferring dockerfile: 2.78kB                                                                                            0.0s
 => [internal] load metadata for docker.io/library/ubuntu:jammy                                                                   1.8s
 => [internal] load metadata for docker.io/library/swift:5.7-jammy                                                                1.8s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                     0.0s
 => [auth] library/swift:pull token for registry-1.docker.io                                                                      0.0s
 => CACHED [build  1/12] FROM docker.io/library/swift:5.7-jammy@sha256:e1da6de0a96b09438cfff68e7ab757eca073102fb34b5eaa637249545  0.0s
 => => resolve docker.io/library/swift:5.7-jammy@sha256:e1da6de0a96b09438cfff68e7ab757eca073102fb34b5eaa63724954536e9897          0.0s
 => [internal] load build context                                                                                                 0.0s
 => => transferring context: 40.24kB                                                                                              0.0s
 => [stage-1 1/5] FROM docker.io/library/ubuntu:jammy@sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f     0.0s
 => => resolve docker.io/library/ubuntu:jammy@sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f             0.0s
 => [build  2/12] RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true     && apt-get -q update     && ap  38.9s
 => [build  3/12] WORKDIR /build                                                                                                  0.0s
 => [build  4/12] COPY ./Package.* ./                                                                                             0.0s
 => [build  5/12] RUN swift package resolve                                                                                     198.2s
 => [build  6/12] COPY . .                                                                                                        0.0s
 => ERROR [build  7/12] RUN swift build -c release --static-swift-stdlib                                                         30.8s
------
 > [build  7/12] RUN swift build -c release --static-swift-stdlib:
#0 13.67 error: 'swift-algorithms': Invalid manifest
#0 13.67 qemu: uncaught target signal 4 (Illegal instruction) - core dumped
------
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
WARNING: failed to get git remote url: fatal: No remote configured to list refs from.
Dockerfile:26
--------------------
  24 |
  25 |     # Build everything, with optimizations
  26 | >>> RUN swift build -c release --static-swift-stdlib
  27 |
  28 |     # Switch to the staging area
--------------------
ERROR: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c swift build -c release --static-swift-stdlib" did not complete successfully: exit code: 1
```

### Expected behavior

The `docker buildx build` command should produce a cross-platform image without error.

### Environment

* Vapor Framework version: 4.69.2
* Vapor Toolbox version: 18.6.0
* OS version: macOS 13.2.1

### Additional context

I have had some luck getting builds to work by inserting `QEMU_CPU=max` into the `RUN swift` commands in the Dockerfile and by prefixing my `docker buildx build` command with this environment variable. However, the results are inconsistent, and I'm having trouble narrowing down exactly where this environment variable is needed to produce reliable builds.

**Comment by 0xTim** [comment]
@samalone Thanks for filing this. Unfortunately there's not a lot as Vapor we can do. ARM->x6 emulation via QEMU has always been a bit flaky and you'll hit issues with any sufficiently large project. The best option is to file this on Swift itself and they can investigate it to see if it's a compiler issue or something that needs to be raised on QEMU

**Comment by skibinalexander** [comment]
> @samalone Thanks for filing this. Unfortunately there's not a lot as Vapor we can do. ARM->x6 emulation via QEMU has always been a bit flaky and you'll hit issues with any sufficiently large project. The best option is to file this on Swift itself and they can investigate it to see if it's a compiler issue or something that needs to be raised on QEMU

Thank you for your answer, tell me if there is a solution to build a Docker image of vapor for amd64 ?

**Comment by 0xTim** [comment]
Easy option is to build it in an amd64 environment like GH actions
